// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gylekyesvfqwbzyqmswh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5bGVreWVzdmZxd2J6eXFtc3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MjM0MDMsImV4cCI6MjA4ODk5OTQwM30.QPjES01Up1fHi5wRjNPnj4NXaeplnCxhj8ST4u9WCCg";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);